name: 🐞 Bug report
description: Report a reproducible bug in the project
title: "[BUG] <short description>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug! Please fill in the details below."

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Short description of the issue
      placeholder: App crashes when clicking submit
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Exact steps that trigger the bug
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: It should ...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: It actually ...
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, version, Node, browser, etc.
