name: 💡 Feature request
description: Suggest an idea or improvement
title: "[Feature] <short description>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "We appreciate ideas to make this project better!"

  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Short summary of the feature
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Detailed Description
      placeholder: Explain how it works and why it’s useful

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Describe any alternate solutions

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Add any screenshots or references
